<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-8">
            <h1>History</h1>

            <table class="table">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Link</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($items as $item):?>
                        <tr>
                            <td> <?= $item['date_time'] ?> </td><td><a href="<?= $item['source'] ?>" target="_blank"><?= $item['source'] ?></a></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>