<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">

    <?=
	$this->headTitle('Aid - Project')->setSeparator(' - ')->setAutoEscape(false);

//		$this->headMeta()
//		->appendName('viewport', 'width=device-width, initial-scale=1.0')
//		->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
//		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')

//		$this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('/shop/img/favicon.png')])
//			->prependStylesheet($this->basePath('/statics/bootstrap-4.0.0/dist/css/bootstrap.css'))
//		->prependStylesheet($this->basePath('shop/css/bootstrap.css'))

//      $this->headScript()
//		->prependFile($this->basePath('shop/js/bootstrap.bundle.js'))
//		->prependFile($this->basePath('shop/js/bootstrap.js'))
//		->prependFile($this->basePath('shop/js/jquery.mask.js'))
//		->prependFile($this->basePath('shop/js/chart.js/Chart.js'))
//		->prependFile($this->basePath('shop/js/chart.js/Chart.bundle.js'))
//		->prependFile($this->basePath('shop/js/jquery-3.1.0.min.js'))
	?>

	<!-- Bootstrap core CSS -->
	<link href="/statics/aidview/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

	<!-- Custom fonts for this template -->
	<link href="/statics/aidview/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

	<!-- Plugin CSS -->
	<link href="/statics/aidview/vendor/magnific-popup/magnific-popup.css" rel="stylesheet" type="text/css">

	<!-- Custom styles for this template -->
	<link href="/statics/aidview/css/freelancer.min.css" rel="stylesheet">

</head>



<body id="page-top">

<!-- Navigation -->
<nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav">
	<div class="container">
		<a class="navbar-brand js-scroll-trigger" href="#page-top">aid - project</a>
		<button class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			Menu
			<i class="fa fa-bars"></i>
		</button>
		<div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item mx-0 mx-lg-1">
					<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#portfolio">Как это работает</a>
				</li>
				<li class="nav-item mx-0 mx-lg-1">
					<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#about">Типы работ</a>
				</li>
				<li class="nav-item mx-0 mx-lg-1">
					<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#contact">Контакты</a>
				</li>
				<li class="nav-item mx-0 mx-lg-1">
					<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="tel:+79163000927">+7 (916) 300-09-27</a>
				</li>
			</ul>
		</div>
	</div>
</nav>

<!-- Header -->
<header class="masthead bg-primary text-white text-center">
	<div class="container">
		<img class="img-fluid mb-5 d-block mx-auto" src="/statics/aidview/img/profile.png" alt="">
		<h1 class="text-uppercase mb-0">Вызвать мастера?</h1>
		<hr class="star-light">
		<h2 class="font-weight-light mb-0">Мастер для работ любых типов</h2>
	</div>
</header>

<!-- Portfolio Grid Section -->
<section class="portfolio" id="portfolio">
	<div class="container">
		<h2 class="text-center text-uppercase text-secondary mb-0">Как это работает</h2>
		<hr class="star-dark mb-5">
		<div class="row">
			<div class="col-md-12 col-lg-12 text-center">
				Вы оставляете заявку, мы подбираем мастера в соответсвие с вашей задачей и в течение часа он приезжает к вам.
				Стоимость вызова фиксированная и состовляет 500 рублей. После диагностики, мастер скажит окончательную стоимость.<br />
				Диагностика входит в стоимость вызова.
				<br />
				<br />
				После того как мастер выполнит свою работу вы можете оставить отзыв о мастере и порекомендовать его другим участникам системы.
			</div>
		</div>
	</div>
</section>

<!-- About Section -->
<section class="bg-primary text-white mb-0" id="about">
	<div class="container">
		<h2 class="text-center text-uppercase text-white">Типы работ</h2>
		<hr class="star-light mb-5">
		<div class="row">
			<div class="col-lg-4 ml-auto">
				<p class="lead">
				<ul>
					<li>Мелкий ремонт</li>
					<li>Электрик</li>
					<li>Плотник</li>
					<li>Сантехник</li>
					<li>Плиточник</li>
					<li>Маляр</li>
					<li>Штукатур</li>
				</ul>
				</p>
			</div>
			<div class="col-lg-4 mr-auto">
				<p class="lead">
				<ul>
					<li>Ремонт стиральной машинки</li>
					<li>Ремонт компьютера</li>
					<li>Ремонт телевизора</li>
					<li>Ремонт микроволновой пичи</li>
					<li>Ремонт телефонов</li>
					<li>Ремонт планшетов</li>
					<li>Ремонт бытовой электроники</li>
				</ul>
				</p>
			</div>
		</div>

	</div>
</section>

<!-- Contact Section -->
<section id="contact">
	<div class="container">
		<h2 class="text-center text-uppercase text-secondary mb-0">оставить заявку</h2>
		<hr class="star-dark mb-5">
		<div class="row">
			<div class="col-lg-8 mx-auto">
				<!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
				<!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
				<form name="sentMessage" id="contactForm" novalidate="novalidate">
					<div class="control-group">
						<div class="form-group floating-label-form-group controls mb-0 pb-2">
							<label>Name</label>
							<input class="form-control" id="name" type="text" placeholder="Имя" required="required" data-validation-required-message="Please enter your name.">
							<p class="help-block text-danger"></p>
						</div>
					</div>
					<div class="control-group">
						<div class="form-group floating-label-form-group controls mb-0 pb-2">
							<label>Email Address</label>
							<input class="form-control" id="email" type="email" placeholder="Email адрес" required="required" data-validation-required-message="Please enter your email address.">
							<p class="help-block text-danger"></p>
						</div>
					</div>
					<div class="control-group">
						<div class="form-group floating-label-form-group controls mb-0 pb-2">
							<label>Phone Number</label>
							<input class="form-control" id="phone" type="tel" placeholder="Номер телефона" required="required" data-validation-required-message="Please enter your phone number.">
							<p class="help-block text-danger"></p>
						</div>
					</div>
					<div class="control-group">
						<div class="form-group floating-label-form-group controls mb-0 pb-2">
							<label>Message</label>
							<textarea class="form-control" id="message" rows="5" placeholder="Опишите что случилось" required="required" data-validation-required-message="Please enter a message."></textarea>
							<p class="help-block text-danger"></p>
						</div>
					</div>
					<br>
					<div id="success"></div>
					<div class="form-group">
						<button type="submit" class="btn btn-primary btn-xl" id="sendMessageButton">Send</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</section>

<!-- Footer -->
<footer class="footer text-center">
	<div class="container">
		<div class="row">
			<div class="col-md-4 mb-5 mb-lg-0">
				<h4 class="text-uppercase mb-4">Офис</h4>
				<p class="lead mb-0">Перервинский б-р
					<br > д 15 к 2
				</p>
			</div>
			<div class="col-md-4 mb-5 mb-lg-0">
				<h4 class="text-uppercase mb-4">Мы в соц сетях</h4>
				<ul class="list-inline mb-0">
					<li class="list-inline-item">
						<a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
							<i class="fa fa-fw fa-facebook"></i>
						</a>
					</li>
					<li class="list-inline-item">
						<a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
							<i class="fa fa-fw fa-google-plus"></i>
						</a>
					</li>
					<li class="list-inline-item">
						<a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
							<i class="fa fa-fw fa-twitter"></i>
						</a>
					</li>
					<li class="list-inline-item">
						<a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
							<i class="fa fa-fw fa-linkedin"></i>
						</a>
					</li>
					<li class="list-inline-item">
						<a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
							<i class="fa fa-fw fa-dribbble"></i>
						</a>
					</li>
				</ul>
			</div>
			<div class="col-md-4">
				<h4 class="text-uppercase mb-4">О нас</h4>
				<p class="lead mb-0">
					открытый проект создан для избавление от машеников и лиц  не добросоветсно выполняющих свои обязонасти.
			</div>
		</div>
	</div>
</footer>

<div class="copyright py-4 text-center text-white">
	<div class="container">
		<small>Copyright &copy; Your Website 2015 - 2018</small>
	</div>
</div>

<!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
<div class="scroll-to-top d-lg-none position-fixed ">
	<a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
		<i class="fa fa-chevron-up"></i>
	</a>
</div>

<!-- Bootstrap core JavaScript -->
<script src="/statics/aidview/vendor/jquery/jquery.min.js"></script>
<script src="/statics/aidview/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Plugin JavaScript -->
<script src="/statics/aidview/vendor/jquery-easing/jquery.easing.min.js"></script>
<script src="/statics/aidview/vendor/magnific-popup/jquery.magnific-popup.min.js"></script>

<!-- Contact Form JavaScript -->
<script src="/statics/aidview/js/jqBootstrapValidation.js"></script>
<script src="/statics/aidview/js/contact_me.js"></script>

<!-- Custom scripts for this template -->
<script src="/statics/aidview/js/freelancer.min.js"></script>




<?php //echo $this->content ?>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
</body>

</html>
