<!doctype html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <?=
        $this->headTitle('IGP - Image generate pro')->setSeparator(' - ')->setAutoEscape(false);
        $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"
              integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    </head>
    <body>
        <div class="container">
            <br/>
            <div class="row justify-content-center">
                <div style="margin-top: 10%" class="col-12 col-md-10 col-lg-8">
                    <form class="card card-sm" method="post">

                        <?php if(!empty($newlink)): ?>
                            <div class="input-group card-body row no-gutters align-items-center">
                                <?=$newlink ?>
                            </div>
                        <?php endif; ?>
                        <div class="input-group card-body row no-gutters align-items-center">
                            <!--end of col-->
                            <div class="col">
                                <input class="form-control form-control-lg form-control-borderless" type="text"
                                       style="border-top-right-radius: 0px; border-bottom-right-radius: 0px" name="source"
                                       placeholder="Enter URL">
                            </div>
                            <!--end of col-->
                            <div class="input-group-append col-auto">
                                <button class="btn btn-lg btn-success" type="submit">Generate</button>
                            </div>
                            <!--end of col-->
                        </div>
                    </form>
                </div>
                <!--end of col-->
            </div>
        </div>
    </body>
</html>

