<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">

        <?=
        $this->headTitle('IGP - Image generate pro')->setSeparator(' - ')->setAutoEscape(false);
        $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <link href="/static/style/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <link rel="stylesheet" href="/static/style/all.css"
              integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

        <script src="/static/javascript/jquery.min.js"></script>
        <script src="/static/javascript/bootstrap.min.js"></script>
    </head>
    <body>
        <div class="container">
            <br/>
            <div class="row justify-content-center">
                <div style="margin-top: 10%" class="col-12 col-md-10 col-lg-8">
                    <form id="formgenerate" class="card card-sm" method="post">

                        <?php if(!empty($newlink)): ?>
                            <div class="input-group card-body row no-gutters align-items-center">
                                <?=$newlink ?>
                            </div>
                        <?php endif; ?>
                        <div class="input-group card-body row no-gutters align-items-center">
                            <!--end of col-->
                            <div class="col">
                                <input id="inputsource" class="form-control form-control-lg form-control-borderless" type="text"
                                       style="border-top-right-radius: 0px; border-bottom-right-radius: 0px" name="source"
                                       placeholder="Enter URL">
                            </div>
                            <!--end of col-->
                            <div class="input-group-append col-auto">
                                <button id="buttongenerate" class="btn btn-lg btn-success" type="submit">Generate</button>
                            </div>
                            <!--end of col-->
                        </div>
                    </form>
                </div>
                <!--end of col-->
            </div>
        </div>
        <script>
            $(function(){

                var form = {
                    body: $( "#formgenerate" ),
                    button: $( "#buttongenerate" ),
                    input: $( "#inputsource" )
                };

                var label = {
                    gener: "Generate",
                    clear: "Clear"
                };

                form.input.keyup( function(){
                    if(form.button.text() == label.clear) {
                        form.button.text(label.gener);
                    }
                });
                
                form.body.on( "submit", function( event ) {
                    event.preventDefault();

                    if(form.button.text() == label.clear){
                        form.input.val("");
                        form.button.text(label.gener);
                    }else{
                        $.ajax({
                            type: "POST",
                            url: '/',
                            cache: false,
                            async: false,
                            data: $( this ).serialize(),
                            success: function(success){
                                form.input.val(success);
                                form.button.text(label.clear);
                            }
                        }).done(function(){
                            var copyText = document.getElementById("inputsource");
                            /* Select the text field */
                            copyText.select();
                            /* Copy the text inside the text field */
                            document.execCommand("copy");
                            /* Alert the copied text */
                            alert("Copied the text: " + copyText.value);
                        });
                    }

                });


            });

        </script>
    </body>
</html>
