<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">

    <?=
	$this->headTitle('Aid - Project')->setSeparator(' - ')->setAutoEscape(false);
//		$this->headMeta()
//		->appendName('viewport', 'width=device-width, initial-scale=1.0')
//		->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
//		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')

//		$this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('/shop/img/favicon.png')])
//			->prependStylesheet($this->basePath('/statics/bootstrap-4.0.0/dist/css/bootstrap.css'))
//		->prependStylesheet($this->basePath('shop/css/bootstrap.css'))

//      $this->headScript()
//		->prependFile($this->basePath('shop/js/bootstrap.bundle.js'))
//		->prependFile($this->basePath('shop/js/bootstrap.js'))
//		->prependFile($this->basePath('shop/js/jquery.mask.js'))
//		->prependFile($this->basePath('shop/js/chart.js/Chart.js'))
//		->prependFile($this->basePath('shop/js/chart.js/Chart.bundle.js'))
//		->prependFile($this->basePath('shop/js/jquery-3.1.0.min.js'))
	?>
	<!-- Bootstrap core CSS -->
	<link href="/statics/aidview/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
	<!-- Custom fonts for this template -->
	<link href="/statics/aidview/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
	<!-- Plugin CSS -->
	<link href="/statics/aidview/vendor/magnific-popup/magnific-popup.css" rel="stylesheet" type="text/css">
	<!-- Custom styles for this template -->
	<link href="/statics/aidview/css/freelancer.min.css" rel="stylesheet">
</head>

<body>
    <form method="post">
        <input style="margin: 20px" type="text" name="source" placeholder="enter source link">
        <input type="submit" value="generate">
    </form>
</body>

</html>
