<?php
/**
 * @link      http://github.com/zendframework/ZendSkeletonApplication for the canonical source repository
 * @copyright Copyright (c) 2005-2016 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   http://framework.zend.com/license/new-bsd New BSD License
 */

namespace Application\Controller;

use Application\Model\Base;
use Auth\Helpers\Session;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\Mvc\MvcEvent;
use Zend\View\Model\ViewModel;

class AdminController extends AbstractActionController
{
    private $model;
    private $session;

    function __construct(Base $model, Session $session)
    {
        $this->model = $model;
        $this->session = $session;
    }

    public function onDispatch(MvcEvent $e)
    {
        if(!$this->session->checkSession()){
            return $this->redirect()->toRoute('igp', ['action' => 'login']);
        }
        $this->layout()->setTemplate('layout/admin');

        return parent::onDispatch($e); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        //https://www.10bestdesign.com/jqvmap/
        return new ViewModel();
    }
}
