<?php
/**
 * @link      http://github.com/zendframework/ZendSkeletonApplication for the canonical source repository
 * @copyright Copyright (c) 2005-2016 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   http://framework.zend.com/license/new-bsd New BSD License
 */

namespace Application\Controller;

use Application\Model\FollowLinks;
use Application\Model\Links;
use Auth\Helpers\Session;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\Mvc\MvcEvent;
use Zend\View\Model\ViewModel;

class AdminController extends BaseController
{
    public function onDispatch(MvcEvent $e)
    {
        if($this->getUserId() == 0){
            return $this->redirect()->toRoute('igp', ['action' => 'login']);
        }
        $this->layout()->setTemplate('layout/admin');

        return parent::onDispatch($e); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {

        $userId = $this->getUserId();
        $fl = iterator_to_array($this->followLinks->getCount($userId));
        $colors = '';
        if(!empty($fl)){
            foreach ($fl as $item){
                if($item['count'] > 0 ){
                    $green = 255 - $item['count'] * 2;
                    if($green < 100) $green = 100;
                    $colors .= $item['code_region'].": ". "'rgb(0, {$green}, 58)', ";
                }
            }
        }

        $flTable = iterator_to_array($this->links->followLinks()->getFollowLinks($userId));
        $totalLinks = $this->links->countUserLinks($userId)['c'];
        //https://www.10bestdesign.com/jqvmap/
        return new ViewModel(["colorMap" => $colors, "fl_table" => $flTable, "totalLinks" => $totalLinks]);
    }

    public function activityAction()
    {
        $userId = $this->getUserId();

        $data = [];
        foreach ($this->links->followLinks()->getForTableActivity($userId) as $item){
            $data[] = [$item['date'], (int) $item['count']];
        };
        
        echo json_encode($data, JSON_UNESCAPED_SLASHES);
        die();
    }
}
