<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <?=
    $this->headTitle('Aid - Project')->setSeparator(' - ')->setAutoEscape(false);

    ?>
    <script src="/statics/aidview/vendor/jquery/jquery.js"></script>
    <script src="/statics/aidview/vendor/bootstrap/js/bootstrap.js"></script>
    <script src="/statics/aidview/js/scrollspy.js"></script>

    <!-- Собираем меню -->
    <script>
        $(function () {
            var h4 = $('#documentation-content>h4');
            var prepareMenu = "";
            $.each(h4, function (i, k) {
                var thisItem = $(k);
                var link = "<b><a class=\"nav-link\" href=#"+thisItem.attr('id')+">" + thisItem.text() + "</a></b>";
//                $(".nav.nav-pills.flex-column").append(link);
                prepareMenu += link;

                if($('div.'+thisItem.attr('id')+">h5").has()){
                    $.each($('div.'+thisItem.attr('id')+">h5"), function (is, ks) {
                        var item = $(ks);
                        link = "<nav class=\"nav nav-pills flex-column\">" +
                                    "<a class=\"nav-link ml-3 my-1\" href=#"+item.attr('id')+">" + item.text() + "</a>" +
                                "</nav>";
                        prepareMenu += link;
                    });
                }
                console.log(prepareMenu);
            });

            $(".nav.nav-pills.flex-column").append(prepareMenu);
        });
    </script>

    <style>
        #documentation-content>div{
            padding-left: 25px;
        }
        #documentation-content>div>p{
            padding-left: 25px;
        }
    </style>

    <!-- Bootstrap core CSS -->
    <link href="/statics/aidview/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="/statics/aidview/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Plugin CSS -->
    <link href="/statics/aidview/vendor/magnific-popup/magnific-popup.css" rel="stylesheet" type="text/css">
</head>

<!--body id="page-top" data-spy="scroll" data-target="#navbar-example3" data-offset="10"-->
<body id="page-top">
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#">Billig.<b style="color: blue;">ru </b></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Документация</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/test/handlers">ТЕСТ</a>
                </li>
            </ul>
            <span class="navbar-text">
                      Документация api для проекта billig.ru
                    </span>
        </div>
    </div>
</nav>
<br />
<div class="container">
    <h1>Документация - 1.0</h1>
    <hr />
    <div class="row">
        <div class="col-10">


            <div id="documentation-content">
                <h4 id="item-1">Ресурс</h4>
                <p>Ниже описанны все урлы для отправки запросов</p>
                <div class="item-1">
                    <h5 id="item-1-1">Обработчики</h5>
                    <p>
                        <a href="/aid/k33f3c8db70d437ce41cfbd1bbde0f413/run/orders">orders</a><br />
                        <a href="/aid/k33f3c8db70d437ce41cfbd1bbde0f413/run/users">users</a><br />
                        <a href="/aid/k33f3c8db70d437ce41cfbd1bbde0f413/run/professions">professions</a><br />
                        <a href="/aid/k33f3c8db70d437ce41cfbd1bbde0f413/run/users_address">users_address</a><br />
                        <a href="/aid/k33f3c8db70d437ce41cfbd1bbde0f413/run/users_profession">users_profession</a><br />
                    </p>
                    <h5 id="item-1-2">Дебагер</h5>
                    <p>
                        <a href="/test/handlers">TEST</a>
                    </p>
                </div>


                <h4 id="item-2">Запросы </small></h4>
                <p>Ниже описанны запросы которые можно отправить в обработчики</p>
                <div class="item-2">
                    <h5 id="item-2-1">getItem</h5>
                    <p>
                        Получить данные по условию
                    </p>
                    <h5 id="item-2-2">fetchList</h5>
                    <p>
                        получить список записей
                    </p>
                    <h5 id="item-2-3">add</h5>
                    <p>
                        Добавить или обновить данные (если передан id то обновляем)
                    </p>
                    <h5 id="item-2-4">delete</h5>
                    <p>
                        удаляем данные
                    </p>
                </div>

                <h4 id="item-3"><a href="/aid/k33f3c8db70d437ce41cfbd1bbde0f413/run/users">users</a> </small></h4>
                <p>
                    Ниже описанны данные для создания пользователя
                </p>
                <div class="item-3">
                    <h5 id="item-3-1">add</h5>
                    <p>
                        <b>Обязательнные данные:</b> <br />
                        fname (string) UTF-8 - минимальное количество символов 2 максимальное 16 <br />
                        lname (string) UTF-8 - минимальное количество символов 2 максимальное 16 <br />
                        email (string) UTF-8 - формат email пример: youemail@site.com <br />
                        password (string) UTF-8 - минимальное количество символов 4 максимальное 100 <br />
                    </p>
                    <p>
                        <b>Не обязательнные данные:</b> <br />
                        status (int) - cтус пользователя (бан, подтверждения email и тд)  <br />
                        phone (int) - номер телефона пользователя <br />
                        type (enum('EX', 'CU')) UTF-8: определяет тип пользователя EX - executor исполнитель, CU - customer заказчик<br />
                    </p>
                    <p>
                        <b>Дополнительные данные: </b> <br />
                        is_deleted (enum('0', '1')) - При добавление по умолчанию 0 после выполнения delete проставляется 1  <br />
                        date_update (date) - Дата добавления пользователя или дата обновления данных (если данные менялись)<br />
                    </p>
                </div>

            </div>

        </div>
        <div class="col-2">
            <nav id="navbar-example3" class="navbar navbar-light bg-light">
                <nav class="nav nav-pills flex-column">
                </nav>
            </nav>
        </div>
    </div>
</div>
</body>

</html>